//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Акт приемки.
    /// </summary>
    // *** Start programmer edit section *** (АктПриемки CustomAttributes)

    // *** End programmer edit section *** (АктПриемки CustomAttributes)
    [AutoAltered()]
    [Caption("Акт приемки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АктПриемкиE", new string[] {
            "НомерАкта as \'Номер акта\'",
            "ДатаПриемки as \'Дата приемки\'",
            "Поставщики.Наименование as \'Наименование\'",
            "Сотрудники.ФИОсотрудника as \'Ф и осотрудника\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Поставщики.Наименование",
            "Сотрудники.ФИОсотрудника"})]
    [AssociatedDetailViewAttribute("АктПриемкиE", "ПринятыйМат", "ПринятыйМатE", true, "", "Принятый мат", true, new string[] {
            ""})]
    [View("АктПриемкиL", new string[] {
            "НомерАкта as \'Номер акта\'",
            "ДатаПриемки as \'Дата приемки\'",
            "Поставщики.Наименование as \'Наименование\'",
            "Сотрудники.ФИОсотрудника as \'Ф и осотрудника\'"})]
    public class АктПриемки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерАкта;
        
        private System.DateTime fДатаПриемки;
        
        private IIS.OsipovaE.Поставщики fПоставщики;
        
        private IIS.OsipovaE.Сотрудники fСотрудники;
        
        private IIS.OsipovaE.DetailArrayOfПринятыйМат fПринятыйМат;
        
        // *** Start programmer edit section *** (АктПриемки CustomMembers)

        // *** End programmer edit section *** (АктПриемки CustomMembers)

        
        /// <summary>
        /// ДатаПриемки.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.ДатаПриемки CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.ДатаПриемки CustomAttributes)
        public virtual System.DateTime ДатаПриемки
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Get start)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Get start)
                System.DateTime result = this.fДатаПриемки;
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Get end)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Set start)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Set start)
                this.fДатаПриемки = value;
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Set end)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Set end)
            }
        }
        
        /// <summary>
        /// НомерАкта.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.НомерАкта CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.НомерАкта CustomAttributes)
        public virtual int НомерАкта
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Get start)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Get start)
                int result = this.fНомерАкта;
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Get end)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Set start)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Set start)
                this.fНомерАкта = value;
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Set end)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Set end)
            }
        }
        
        /// <summary>
        /// Акт приемки.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Поставщики CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Поставщики CustomAttributes)
        [PropertyStorage(new string[] {
                "Поставщики"})]
        [NotNull()]
        public virtual IIS.OsipovaE.Поставщики Поставщики
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Поставщики Get start)

                // *** End programmer edit section *** (АктПриемки.Поставщики Get start)
                IIS.OsipovaE.Поставщики result = this.fПоставщики;
                // *** Start programmer edit section *** (АктПриемки.Поставщики Get end)

                // *** End programmer edit section *** (АктПриемки.Поставщики Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Поставщики Set start)

                // *** End programmer edit section *** (АктПриемки.Поставщики Set start)
                this.fПоставщики = value;
                // *** Start programmer edit section *** (АктПриемки.Поставщики Set end)

                // *** End programmer edit section *** (АктПриемки.Поставщики Set end)
            }
        }
        
        /// <summary>
        /// Акт приемки.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.OsipovaE.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Сотрудники Get start)

                // *** End programmer edit section *** (АктПриемки.Сотрудники Get start)
                IIS.OsipovaE.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (АктПриемки.Сотрудники Get end)

                // *** End programmer edit section *** (АктПриемки.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Сотрудники Set start)

                // *** End programmer edit section *** (АктПриемки.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (АктПриемки.Сотрудники Set end)

                // *** End programmer edit section *** (АктПриемки.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Акт приемки.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.ПринятыйМат CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.ПринятыйМат CustomAttributes)
        public virtual IIS.OsipovaE.DetailArrayOfПринятыйМат ПринятыйМат
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.ПринятыйМат Get start)

                // *** End programmer edit section *** (АктПриемки.ПринятыйМат Get start)
                if ((this.fПринятыйМат == null))
                {
                    this.fПринятыйМат = new IIS.OsipovaE.DetailArrayOfПринятыйМат(this);
                }
                IIS.OsipovaE.DetailArrayOfПринятыйМат result = this.fПринятыйМат;
                // *** Start programmer edit section *** (АктПриемки.ПринятыйМат Get end)

                // *** End programmer edit section *** (АктПриемки.ПринятыйМат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.ПринятыйМат Set start)

                // *** End programmer edit section *** (АктПриемки.ПринятыйМат Set start)
                this.fПринятыйМат = value;
                // *** Start programmer edit section *** (АктПриемки.ПринятыйМат Set end)

                // *** End programmer edit section *** (АктПриемки.ПринятыйМат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АктПриемкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктПриемкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктПриемкиE", typeof(IIS.OsipovaE.АктПриемки));
                }
            }
            
            /// <summary>
            /// "АктПриемкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктПриемкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктПриемкиL", typeof(IIS.OsipovaE.АктПриемки));
                }
            }
        }
    }
}
