//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОзаказчика as \'Ф и озаказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособПолучения as \'Способ получения\'",
            "Номенклатура.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Номенклатура.Наименование"})]
    [View("ЗаказL", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОзаказчика as \'Ф и озаказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособПолучения as \'Способ получения\'",
            "Номенклатура.Наименование as \'Наименование\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаказа;
        
        private string fФИОзаказчика;
        
        private string fАдресЗаказа;
        
        private IIS.OsipovaE.СпособДоставки fСпособПолучения;
        
        private IIS.OsipovaE.Номенклатура fНоменклатура;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// АдресЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.АдресЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string АдресЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get start)
                string result = this.fАдресЗаказа;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Get end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set start)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set start)
                this.fАдресЗаказа = value;
                // *** Start programmer edit section *** (Заказ.АдресЗаказа Set end)

                // *** End programmer edit section *** (Заказ.АдресЗаказа Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// СпособПолучения.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СпособПолучения CustomAttributes)

        // *** End programmer edit section *** (Заказ.СпособПолучения CustomAttributes)
        public virtual IIS.OsipovaE.СпособДоставки СпособПолучения
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СпособПолучения Get start)

                // *** End programmer edit section *** (Заказ.СпособПолучения Get start)
                IIS.OsipovaE.СпособДоставки result = this.fСпособПолучения;
                // *** Start programmer edit section *** (Заказ.СпособПолучения Get end)

                // *** End programmer edit section *** (Заказ.СпособПолучения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СпособПолучения Set start)

                // *** End programmer edit section *** (Заказ.СпособПолучения Set start)
                this.fСпособПолучения = value;
                // *** Start programmer edit section *** (Заказ.СпособПолучения Set end)

                // *** End programmer edit section *** (Заказ.СпособПолучения Set end)
            }
        }
        
        /// <summary>
        /// ФИОзаказчика.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ФИОзаказчика CustomAttributes)

        // *** End programmer edit section *** (Заказ.ФИОзаказчика CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОзаказчика
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ФИОзаказчика Get start)

                // *** End programmer edit section *** (Заказ.ФИОзаказчика Get start)
                string result = this.fФИОзаказчика;
                // *** Start programmer edit section *** (Заказ.ФИОзаказчика Get end)

                // *** End programmer edit section *** (Заказ.ФИОзаказчика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ФИОзаказчика Set start)

                // *** End programmer edit section *** (Заказ.ФИОзаказчика Set start)
                this.fФИОзаказчика = value;
                // *** Start programmer edit section *** (Заказ.ФИОзаказчика Set end)

                // *** End programmer edit section *** (Заказ.ФИОзаказчика Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Заказ.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.OsipovaE.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Номенклатура Get start)

                // *** End programmer edit section *** (Заказ.Номенклатура Get start)
                IIS.OsipovaE.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (Заказ.Номенклатура Get end)

                // *** End programmer edit section *** (Заказ.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Номенклатура Set start)

                // *** End programmer edit section *** (Заказ.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Заказ.Номенклатура Set end)

                // *** End programmer edit section *** (Заказ.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.OsipovaE.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.OsipovaE.Заказ));
                }
            }
        }
    }
}
