//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "КодМатериала as \'Код материала\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [View("НоменклатураL", new string[] {
            "КодМатериала as \'Код материала\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодМатериала;
        
        private string fНаименование;
        
        private double fСтоимость;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// КодМатериала.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.КодМатериала CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.КодМатериала CustomAttributes)
        public virtual int КодМатериала
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Get start)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Get start)
                int result = this.fКодМатериала;
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Get end)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Set start)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Set start)
                this.fКодМатериала = value;
                // *** Start programmer edit section *** (Номенклатура.КодМатериала Set end)

                // *** End programmer edit section *** (Номенклатура.КодМатериала Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Наименование CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Get start)

                // *** End programmer edit section *** (Номенклатура.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Номенклатура.Наименование Get end)

                // *** End programmer edit section *** (Номенклатура.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Set start)

                // *** End programmer edit section *** (Номенклатура.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Номенклатура.Наименование Set end)

                // *** End programmer edit section *** (Номенклатура.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Стоимость Get start)

                // *** End programmer edit section *** (Номенклатура.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Номенклатура.Стоимость Get end)

                // *** End programmer edit section *** (Номенклатура.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Стоимость Set start)

                // *** End programmer edit section *** (Номенклатура.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Номенклатура.Стоимость Set end)

                // *** End programmer edit section *** (Номенклатура.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.OsipovaE.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.OsipovaE.Номенклатура));
                }
            }
        }
    }
}
