//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Принятый мат.
    /// </summary>
    // *** Start programmer edit section *** (ПринятыйМат CustomAttributes)

    // *** End programmer edit section *** (ПринятыйМат CustomAttributes)
    [AutoAltered()]
    [Caption("Принятый мат")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПринятыйМатE", new string[] {
            "НомерПозиции as \'Номер позиции\'",
            "Номенклатура.Наименование as \'Наименование\'",
            "Колво as \'Колво\'",
            "Склад.ИмяСклада as \'Имя склада\'"}, Hidden=new string[] {
            "Номенклатура.Наименование",
            "Склад.ИмяСклада"})]
    public class ПринятыйМат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПозиции;
        
        private int fКолво;
        
        private IIS.OsipovaE.Номенклатура fНоменклатура;
        
        private IIS.OsipovaE.Склад fСклад;
        
        private IIS.OsipovaE.АктПриемки fАктПриемки;
        
        // *** Start programmer edit section *** (ПринятыйМат CustomMembers)

        // *** End programmer edit section *** (ПринятыйМат CustomMembers)

        
        /// <summary>
        /// Колво.
        /// </summary>
        // *** Start programmer edit section *** (ПринятыйМат.Колво CustomAttributes)

        // *** End programmer edit section *** (ПринятыйМат.Колво CustomAttributes)
        public virtual int Колво
        {
            get
            {
                // *** Start programmer edit section *** (ПринятыйМат.Колво Get start)

                // *** End programmer edit section *** (ПринятыйМат.Колво Get start)
                int result = this.fКолво;
                // *** Start programmer edit section *** (ПринятыйМат.Колво Get end)

                // *** End programmer edit section *** (ПринятыйМат.Колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПринятыйМат.Колво Set start)

                // *** End programmer edit section *** (ПринятыйМат.Колво Set start)
                this.fКолво = value;
                // *** Start programmer edit section *** (ПринятыйМат.Колво Set end)

                // *** End programmer edit section *** (ПринятыйМат.Колво Set end)
            }
        }
        
        /// <summary>
        /// НомерПозиции.
        /// </summary>
        // *** Start programmer edit section *** (ПринятыйМат.НомерПозиции CustomAttributes)

        // *** End programmer edit section *** (ПринятыйМат.НомерПозиции CustomAttributes)
        public virtual int НомерПозиции
        {
            get
            {
                // *** Start programmer edit section *** (ПринятыйМат.НомерПозиции Get start)

                // *** End programmer edit section *** (ПринятыйМат.НомерПозиции Get start)
                int result = this.fНомерПозиции;
                // *** Start programmer edit section *** (ПринятыйМат.НомерПозиции Get end)

                // *** End programmer edit section *** (ПринятыйМат.НомерПозиции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПринятыйМат.НомерПозиции Set start)

                // *** End programmer edit section *** (ПринятыйМат.НомерПозиции Set start)
                this.fНомерПозиции = value;
                // *** Start programmer edit section *** (ПринятыйМат.НомерПозиции Set end)

                // *** End programmer edit section *** (ПринятыйМат.НомерПозиции Set end)
            }
        }
        
        /// <summary>
        /// Принятый мат.
        /// </summary>
        // *** Start programmer edit section *** (ПринятыйМат.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ПринятыйМат.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.OsipovaE.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ПринятыйМат.Номенклатура Get start)

                // *** End programmer edit section *** (ПринятыйМат.Номенклатура Get start)
                IIS.OsipovaE.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ПринятыйМат.Номенклатура Get end)

                // *** End programmer edit section *** (ПринятыйМат.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПринятыйМат.Номенклатура Set start)

                // *** End programmer edit section *** (ПринятыйМат.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ПринятыйМат.Номенклатура Set end)

                // *** End programmer edit section *** (ПринятыйМат.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Принятый мат.
        /// </summary>
        // *** Start programmer edit section *** (ПринятыйМат.Склад CustomAttributes)

        // *** End programmer edit section *** (ПринятыйМат.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.OsipovaE.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (ПринятыйМат.Склад Get start)

                // *** End programmer edit section *** (ПринятыйМат.Склад Get start)
                IIS.OsipovaE.Склад result = this.fСклад;
                // *** Start programmer edit section *** (ПринятыйМат.Склад Get end)

                // *** End programmer edit section *** (ПринятыйМат.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПринятыйМат.Склад Set start)

                // *** End programmer edit section *** (ПринятыйМат.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (ПринятыйМат.Склад Set end)

                // *** End programmer edit section *** (ПринятыйМат.Склад Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.OsipovaE.АктПриемки.
        /// </summary>
        // *** Start programmer edit section *** (ПринятыйМат.АктПриемки CustomAttributes)

        // *** End programmer edit section *** (ПринятыйМат.АктПриемки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "АктПриемки"})]
        public virtual IIS.OsipovaE.АктПриемки АктПриемки
        {
            get
            {
                // *** Start programmer edit section *** (ПринятыйМат.АктПриемки Get start)

                // *** End programmer edit section *** (ПринятыйМат.АктПриемки Get start)
                IIS.OsipovaE.АктПриемки result = this.fАктПриемки;
                // *** Start programmer edit section *** (ПринятыйМат.АктПриемки Get end)

                // *** End programmer edit section *** (ПринятыйМат.АктПриемки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПринятыйМат.АктПриемки Set start)

                // *** End programmer edit section *** (ПринятыйМат.АктПриемки Set start)
                this.fАктПриемки = value;
                // *** Start programmer edit section *** (ПринятыйМат.АктПриемки Set end)

                // *** End programmer edit section *** (ПринятыйМат.АктПриемки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПринятыйМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПринятыйМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПринятыйМатE", typeof(IIS.OsipovaE.ПринятыйМат));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПринятыйМат.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПринятыйМат CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПринятыйМат CustomAttributes)
    public class DetailArrayOfПринятыйМат : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.OsipovaE.DetailArrayOfПринятыйМат members)

        // *** End programmer edit section *** (IIS.OsipovaE.DetailArrayOfПринятыйМат members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПринятыйМат by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПринятыйМат.
        /// </summary>
        public DetailArrayOfПринятыйМат(IIS.OsipovaE.АктПриемки fАктПриемки) : 
                base(typeof(ПринятыйМат), ((ICSSoft.STORMNET.DataObject)(fАктПриемки)))
        {
        }
        
        public IIS.OsipovaE.ПринятыйМат this[int index]
        {
            get
            {
                return ((IIS.OsipovaE.ПринятыйМат)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.OsipovaE.ПринятыйМат dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
