//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OsipovaE
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Способ доставки.
    /// </summary>
    // *** Start programmer edit section *** (СпособДоставки CustomAttributes)

    // *** End programmer edit section *** (СпособДоставки CustomAttributes)
    public enum СпособДоставки
    {
        
        // *** Start programmer edit section *** (СпособДоставки.Курьер CustomAttributes)

        // *** End programmer edit section *** (СпособДоставки.Курьер CustomAttributes)
        Курьер,
        
        // *** Start programmer edit section *** (СпособДоставки.Самовывоз CustomAttributes)

        // *** End programmer edit section *** (СпособДоставки.Самовывоз CustomAttributes)
        Самовывоз,
    }
}
